<a href="https://colab.research.google.com/github/moath177/flyrank/blob/main/work/notebooks/w02_ml_task_framing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ML-03 — Frame Your Lane as an ML Task

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/moath177/flyrank/blob/main/work/notebooks/w02_ml_task_framing.ipynb)

This skeleton is yours to fill. Work the sections **in order** — each one has a one-line hint. Simple words, honest numbers.

> Working with an AI assistant? Tell it to read `skills/README.md` first and load the one skill this assignment names on its card.

In [1]:
import os, sys, subprocess

IN_COLAB = "google.colab" in sys.modules
REPO_URL = "https://github.com/flyrank-bih/flyrank-ml-internship-starter"
REPO_DIR = "flyrank-ml-internship-starter"

if IN_COLAB:
    if not os.path.isdir(REPO_DIR):
        subprocess.run(["git", "clone", "--depth", "1", REPO_URL, REPO_DIR], check=True)
    os.chdir(REPO_DIR)
    subprocess.run([sys.executable, "-m", "pip", "install", "-q", "-r", "requirements.txt"], check=True)
elif os.path.basename(os.getcwd()) == "notebooks":
    os.chdir("..")  # move from notebooks/ to the repo root

print("Working dir:", os.getcwd())
assert os.path.exists("data/raw/content_refresh_anonymized.csv"), "starter CSV not found — are you at the repo root?"
print("Starter data found. You're ready.")

import pandas as pd, numpy as np
df = pd.read_csv("data/raw/content_refresh_anonymized.csv")
print(df.shape[0], "rows,", df.shape[1], "columns")
df.head(3)

Working dir: /content/flyrank-ml-internship-starter
Starter data found. You're ready.
30000 rows, 44 columns

,content_id,client_id,search_volume,competition,competition_level,cpc,content_type,main_intent,word_count,char_count,...,char_count_tier,ctr,avg_position,engagement_rate,scroll_rate,ai_traffic_pct,impression_tier,position_tier,trend_direction,trend_pct
0,content_304f48230142,client_f369cb89fc,10.0,0.67,HIGH,2.05,keyword article,transactional,3221.0,20457.0,...,15000-25000,0.76,10.6,5.88,4.55,0.0,good,striking,down,-41.4
1,content_a1fb4e703a9e,client_4e07408562,90.0,0.01,LOW,0.05,keyword article,informational,2481.0,15562.0,...,15000-25000,0.05,20.3,0.00,10.00,0.0,good,page_3_5,down,-57.7
2,content_9aa793d4d895,client_7f2253d7e2,0.0,0.00,LOW,0.00,keyword article,informational,3515.0,23643.0,...,15000-25000,0.09,36.5,0.00,28.57,0.0,good,page_3_5,down,-60.9

## 1. My lane as an ML task (type)

*Classification, clustering, ranking, or scoring — which one, and why?*

#**Task type: Ranking / Scoring**

My lane (CTR / Engagement Opportunity Scoring) is not a yes/no problem, so it is
not classification. Whether a page is an "opportunity" is not binary — the gap
between a page's actual CTR and the CTR expected for its position tier is a
continuous, graded signal: some pages sit barely below expectation, others sit
far below it. Picking one fixed cutoff (e.g. `ctr < 0.5`) would collapse that
gradient into an arbitrary yes/no split, and it wouldn't match the decision I'm
actually supporting: "which page should the editor review first?" — that needs
an ordered list, not a flag. So the natural mapping is ranking/scoring: score
every page by its opportunity gap, then rank so limited reviewer time goes to
the top of the list first.

## 2. Target or proxy

*What would you predict? Where does that label come from — observed outcome or a defined rule?*

#**Proxy: impressions-weighted CTR opportunity gap — engineered, not observed as a ready-made column**

The raw signals (`ctr`, `position_tier`, `impressions_90d`) are observed: real, measured
columns in the dataset. But the score I actually rank by does not exist as-is — I build it
myself, in three steps.

**Step 0 — keep only pages with a real position signal.** Pages with `position_tier ==
"no_data"` have `avg_position == 0`, meaning GSC never recorded a ranking for them. Averaging
`ctr` over that group wouldn't mean "normal performance for that rank" — it would just be an
average over pages with no ranking signal at all. These rows are excluded before anything
else is computed, so every tier-level average below only compares pages against others that
actually share a real position.

**Step 1 — the raw gap:**

    expected_ctr(tier) = mean(ctr) across valid pages in that position_tier
    opportunity_gap    = expected_ctr(tier) − ctr

A positive gap means the page underperforms what's normal for its own tier (bigger gap =
bigger opportunity). This stays a continuous score, not a yes/no cutoff — consistent with
the Ranking/Scoring framing from section 1.

**Step 2 — why the raw gap alone isn't enough:** checking `opportunity_gap`'s unique values
showed heavy repetition — thousands of pages shared the exact same gap value. All of them had
`ctr = 0`, which collapses `opportunity_gap` to a constant (`expected_ctr(tier)`) regardless of
how many times the page was actually seen. A page with 5 impressions and a page with 5,000
impressions — both at `ctr = 0` — would get identical scores, even though the second is a far
more reliable, higher-volume opportunity.

**Fix — weight the gap by traffic volume:**

    weighted_score = opportunity_gap × log1p(impressions_90d)

I used `log1p` (not raw `impressions_90d`) because impressions span a huge range (tens to
hundreds of thousands) while the gap only ranges roughly 0–3 — multiplying directly would let
volume dominate the ranking and drown out the gap itself. The log compresses that wide range
(each ×10 increase in impressions becomes a fixed +constant on the log scale) while still
preserving order. `log1p` specifically avoids errors for pages with `impressions_90d = 0`.

**What this score is — and isn't.** `weighted_score` is a practical heuristic: it down-weights
low-volume noise so pages aren't ranked purely on a gap computed from a handful of impressions.
It is **not** a formal statistical confidence measure — it doesn't estimate uncertainty bounds
the way a confidence interval on the true CTR would, it just scales the gap by a rough proxy
for sample size. Sorting by it does surface pages with both a real gap and meaningful traffic,
rather than pages that only look good because of raw volume or a gap that's real but
statistically unreliable due to tiny sample size — but that check is directional, not a proof.

Because I engineered this myself rather than reading a label FlyRank already computed, I have
to be careful it stays a *proxy* for opportunity, not treated as proven ground truth.

In [2]:
import numpy as np

# Step 0: keep only pages with a real position signal
valid = df[df["position_tier"] != "no_data"].copy()

# Step 1: raw gap vs. tier-level expected CTR
expected_ctr = valid.groupby("position_tier")["ctr"].transform("mean")
valid["opportunity_gap"] = expected_ctr - valid["ctr"]

# Step 2: weight by traffic volume so low-impression pages don't dominate/tie
valid["weighted_score"] = valid["opportunity_gap"] * np.log1p(valid["impressions_90d"])

valid[["content_id", "position_tier", "ctr", "impressions_90d",
       "opportunity_gap", "weighted_score"]] \
    .sort_values("weighted_score", ascending=False) \
    .head(10)

,content_id,position_tier,ctr,impressions_90d,opportunity_gap,weighted_score
7678,content_8451fc6f034d,top_3,0.03,272144,1.453611,18.190613
26844,content_8c19996aa890,top_3,0.15,509252,1.333611,17.524576
3331,content_4a6607efcb46,top_3,0.01,128068,1.473611,17.330138
16736,content_e12868d1f396,top_3,0.07,149712,1.413611,16.845255
9412,content_8053a66bd6ac,top_3,0.08,52687,1.403611,15.260254
7860,content_d225ec9f3d46,top_3,0.05,26470,1.433611,14.599610
27107,content_0022a6b4290f,top_3,0.07,29747,1.413611,14.560919
10893,content_6f81ccd92b64,top_3,0.19,73675,1.293611,14.498052
20537,content_f4e210ee0c27,top_3,0.06,24784,1.423611,14.404082
7122,content_7a6df559322d,top_3,0.14,43650,1.343611,14.355110

## 3. Success metric

*One metric you can defend. What number means 'good'?*

#**Metric: Precision@K, K ≈ 25 (assumption)**

Ranking/scoring problems are judged by precision@K: of the top K pages by `weighted_score`,
how many turn out to be genuine opportunities?

**Defining a "hit":** because `weighted_score` is a proxy I engineered (section 2), there is
no ready-made column in the data that says "this page is a genuine opportunity." A hit can
only be defined by an editor manually reviewing a flagged page and confirming it's worth
acting on. That means precision@K is **defined now, but not computable from this static
dataset alone** — it needs either a completed round of human review, or a forward time window
showing CTR actually improved after action (available in the full warehouse, weeks 3+, not in
this 30k-row snapshot).

**Choosing K:** I don't have a real reviewer-capacity number, so I'm assuming one — roughly 5
pages reviewed per day, 5-day work week → K ≈ 25. This is an assumption, not a measured fact,
and I'm stating it as one here rather than treating it as settled.

**What I can do today:** produce the actual top-K list a reviewer would receive, and write the
precision@K function so it's ready to run the moment review labels exist — that's the honest
version of "name the metric before training" when the ground truth doesn't exist yet.

In [5]:
K = 25  # assumption: ~5 pages/day x 5-day work week (see markdown)
top_k[["content_id", "position_tier", "ctr", "impressions_90d", "weighted_score"]]
top_k = valid.sort_values("weighted_score", ascending=False).head(K)



def precision_at_k(is_real_opportunity: pd.Series) -> float:
    """
    is_real_opportunity: one boolean per row of `top_k`, filled in by an editor
    after manually reviewing each flagged page (True = genuine opportunity,
    False = false positive). Not computable from this dataset alone --
    this function is ready to run once that review happens.
    """
    return is_real_opportunity.sum() / len(is_real_opportunity)
print(top_k)

# Example of future use, once review labels exist:
# reviewed = pd.Series([True, True, False, ...])  # one entry per row in top_k
# precision_at_k(reviewed)

                 content_id          client_id  search_volume  competition  \
7678   content_8451fc6f034d  client_d029fa3a95           10.0         1.00
26844  content_8c19996aa890  client_4e07408562           70.0         0.01
3331   content_4a6607efcb46  client_6208ef0f77            0.0         0.00
16736  content_e12868d1f396  client_4e07408562        12100.0         0.01
9412   content_8053a66bd6ac  client_19581e27de            0.0         0.00
7860   content_d225ec9f3d46  client_f369cb89fc            0.0         0.00
27107  content_0022a6b4290f  client_f369cb89fc            0.0         0.00
10893  content_6f81ccd92b64  client_19581e27de           70.0         0.42
20537  content_f4e210ee0c27  client_7f2253d7e2            0.0         0.00
7122   content_7a6df559322d  client_19581e27de           30.0         0.49
21458  content_9009d5d37434  client_6208ef0f77            0.0         0.00
22592  content_f9d82e71e363  client_19581e27de           20.0         0.58
8954   content_cbdf5a78dcd0  client_19581e27de          110.0         0.14
21819  content_4c36c775b818  client_4e07408562           40.0         0.00
16109  content_2d08ccac3f63  client_f369cb89fc            0.0         0.00
12012  content_954cc45bd437  client_4e07408562            0.0         0.00
13601  content_b7bd590fe572  client_19581e27de          590.0         0.06
88     content_998f6f88784c  client_f74efabef1           10.0         0.04
28193  content_6973328a6bb8  client_7f2253d7e2            0.0         0.00
7134   content_31f2223858c8  client_19581e27de            0.0         0.00
22928  content_929aa622b6a0  client_4e07408562            NaN          NaN
25653  content_ddb0d879fa8c  client_19581e27de            0.0         0.00
19781  content_1e5b3a2ba843  client_19581e27de          880.0         0.05
3360   content_9d5d2ad2933c  client_19581e27de            0.0         0.00
3710   content_dcb529347579  client_19581e27de           30.0         0.17

      competition_level    cpc     content_type    main_intent  word_count  \
7678               HIGH  14.11  keyword article  informational      3528.0
26844               LOW   0.00  keyword article  informational      2895.0
3331                LOW   0.00  keyword article  informational      4939.0
16736               LOW   1.36  keyword article  informational      2363.0
9412                LOW   0.00  keyword article  informational         NaN
7860                LOW   0.00  keyword article  informational      2618.0
27107               LOW   0.00  keyword article  informational      2784.0
10893            MEDIUM   1.71  keyword article     commercial         NaN
20537               LOW   0.00  keyword article  informational      4395.0
7122             MEDIUM   1.17  keyword article  transactional      2946.0
21458               LOW   0.00  keyword article  informational      5624.0
22592            MEDIUM   3.07  keyword article  transactional         NaN
8954                LOW   0.09  keyword article  transactional      3187.0
21819               LOW   0.00  keyword article  informational      3097.0
16109               LOW   0.00  keyword article  informational      2723.0
12012               LOW   0.00  keyword article  informational      2910.0
13601               LOW   0.44  keyword article     commercial         NaN
88                  LOW   0.00  keyword article  informational      2964.0
28193               LOW   0.00  keyword article  informational      3527.0
7134                LOW   0.00  keyword article  informational      2850.0
22928               NaN    NaN  keyword article  informational         NaN
25653               LOW   0.00  keyword article  informational         NaN
19781               LOW   0.23  keyword article     commercial      3198.0
3360                LOW   0.00  keyword article  informational      3269.0
3710                LOW   0.05  keyword article     commercial         NaN

       char_count  ... avg_position engagement_rate  scroll_rate  \
7678      24856.0  ...          2.3            2.02         2.26
26844     19343.0  ...          2.5           11.73        16.03
3331      32266.0  ...          2.2            2.30         6.11
16736     15540.0  ...          2.9            5.94        11.97
9412          NaN  ...          2.6            1.92         6.56
7860      18025.0  ...          0.7           10.00        23.08
27107     20150.0  ...          1.2            0.00        10.71
10893         NaN  ...          2.9            2.94         3.16
20537     28348.0  ...          1.6            0.00        20.00
7122      19399.0  ...          0.7           11.59        20.51
21458     37203.0  ...          2.8            4.63        10.20
22592         NaN  ...          2.0            0.00         2.00
8954      21641.0  ...          2.4            0.00         0.00
21819     20514.0  ...          2.3           11.31        18.07
16109     18961.0  ...          2.2           10.00        10.00
12012     18763.0  ...          1.5            0.00         0.00
13601         NaN  ...          2.9            0.00        12.50
88        19813.0  ...          2.6           37.50        37.50
28193     22737.0  ...          1.0            7.69        35.29
7134      19928.0  ...          2.4            0.00         0.00
22928         NaN  ...          2.4            0.00         0.00
25653         NaN  ...          2.9            2.56         4.65
19781     20967.0  ...          2.4           25.00        25.00
3360      22776.0  ...          1.8            4.55         3.85
3710          NaN  ...          1.9            0.00         7.14

       ai_traffic_pct  impression_tier  position_tier  trend_direction  \
7678             2.02        excellent          top_3               up
26844            0.00        excellent          top_3             down
3331             2.30        excellent          top_3               up
16736            0.00        excellent          top_3           stable
9412             0.00        excellent          top_3             down
7860             0.00             good          top_3             down
27107            0.00             good          top_3             down
10893            0.00        excellent          top_3           stable
20537            0.00             good          top_3             down
7122             0.00        excellent          top_3             down
21458            0.00             good          top_3             down
22592            2.27             good          top_3             down
8954             0.00             good          top_3               up
21819            0.00        excellent          top_3             down
16109            0.00             good          top_3             down
12012            0.00             good          top_3             down
13601            0.00             good          top_3             down
88               0.00             good          top_3             down
28193            0.00             good          top_3             down
7134             0.00             good          top_3             down
22928            0.00             good          top_3               up
25653            0.00             good          top_3             down
19781            0.00             good          top_3               up
3360             0.00             good          top_3             down
3710             0.00             good          top_3             down

       trend_pct  opportunity_gap  weighted_score
7678        73.1         1.453611       18.190613
26844      -44.5         1.333611       17.524576
3331      5426.6         1.473611       17.330138
16736      -14.8         1.413611       16.845255
9412       -89.8         1.403611       15.260254
7860       -86.8         1.433611       14.599610
27107      -79.3         1.413611       14.560919
10893        7.1         1.293611       14.498052
20537      -73.4         1.423611       14.404082
7122       -94.7         1.343611       14.355110
21458      -22.2         1.383611       14.183790
22592      -37.8         1.403611       14.171730
8954       184.2         1.463611       14.057210
21819      -33.2         1.073611       14.006008
16109      -75.9         1.413611       13.929841
12012      -88.0         1.443611       13.923215
13601      -86.5         1.463611       13.787142
88         -97.7         1.463611       13.753770
28193      -86.0         1.413611       13.728849
7134       -83.5         1.403611       13.573857
22928       66.8         1.453611       13.566162
25653      -51.2         1.303611       13.359815
19781       54.9         1.453611       13.357397
3360       -58.3         1.383611       13.356932
3710       -69.5         1.413611       13.336741

[25 rows x 46 columns]

## 4. The unit of analysis, as a real dataframe

*Load your lane's slice and show it: one row = one what?*

## 5. Why ML beats a fixed rule here

*What makes the pattern too messy for an if-statement?*

## Self-check

Before you submit, confirm each line honestly:

- [ ] Every section above is filled — markdown thinking AND the code that backs it
- [ ] The notebook runs top to bottom with no errors (Runtime → Run all)
- [ ] No client names, URLs, or private queries anywhere
- [ ] My claims use careful words: observed, measured, directional, decision-support
- [ ] Committed to my repo under `work/notebooks/` — then submit your repo URL on the card. Done.